# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Clean"
license = "MIT"
licenselink = "https://git.sr.ht/~dominicm/website/tree/main/item/LICENSE"
description = "A simple, clean theme made for Dominic's website"
homepage = "https://dominicm.dev"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Dominic Martinez"
  homepage = "https://dominicm.dev"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
